{{- range .Values.apps }}
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: "10"
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "3m"
        {{ if .minScale -}}
        autoscaling.knative.dev/min-scale: "{{ .minScale }}"
        {{- else if .stateful -}}
        autoscaling.knative.dev/min-scale: "{{ .stateful.replicas }}"
        {{- end }}
        autoscaling.knative.dev/max-scale: "3"
      name: {{ $.Release.Name }}-{{ .name }}-{{ $.Values.metadata.commitHash }}
      {{- if and (hasKey $.Values "persistentLogging") (hasKey $.Values.persistentLogging "enabled") $.Values.persistentLogging.enabled }}
      labels:
        gcaas_datadog_enabled: "true"
        service: backend
      {{- end }}
    spec:
      containers:
      - name: user-container
        readinessProbe:
          failureThreshold: 0
          periodSeconds: 0
          successThreshold: 1
          tcpSocket:
            port: 0
          timeoutSeconds: 0
        envFrom:
        - configMapRef:
            name: {{ $.Release.Name }}-config
        - secretRef:
            name: {{ $.Release.Name }}-secret
        image: {{ .image.repository }}/{{ .image.name }}:{{ .image.tag }}
        imagePullPolicy: Always
        resources: {{- toYaml .resources | nindent 12 }}
        ports:
          - containerPort: {{ .image.port }}
        securityContext:
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - name: app-secret
          mountPath: /var/secrets  # Change this to a different path if needed
          readOnly: true
      volumes:
      - name: app-secret
        secret:
          secretName: {{ $.Release.Name }}-secret
---
{{ if .ingress }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ $.Release.Name }}-{{ .name }}-vs
spec:
  gateways:
  - knative-serving/knative-ingress-gateway
  - knative-serving/knative-local-gateway
  hosts:
  - {{ $.Values.metadata.hostName }}
  http:
  - match:
    - uri:
        prefix: '/{{ $.Values.metadata.engagementId }}/{{ $.Release.Name }}-{{ .name }}/'
    rewrite:
        uri: {{ .rewrite.uri }}
    route:
      - destination:
          host: {{ $.Release.Name }}-{{ .name }}-{{ $.Values.metadata.commitHash }}.{{ $.Release.Namespace }}.svc.cluster.local
          port:
            number: 80
        headers:
          request:
            set:
              Knative-Serving-Namespace: {{ $.Release.Namespace }}
              Knative-Serving-Revision: {{ $.Release.Name }}-{{ .name }}-{{ $.Values.metadata.commitHash }}
---
{{- if and (default false $.Values.authentication.entra) $.Values.metadata.entraHostName }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ $.Release.Name }}-{{ .name }}-vs-entra
spec:
  gateways:
  - istio-system/entra-ingress-gateway
  - knative-serving/knative-ingress-gateway
  - knative-serving/knative-local-gateway
  hosts:
  - {{ $.Values.metadata.entraHostName }}
  http:
  - match:
    - uri:
        prefix: '/{{ $.Values.metadata.engagementId }}/{{ $.Release.Name }}-{{ .name }}/'
    rewrite:
        uri: {{ .rewrite.uri }}
    route:
      - destination:
          host: {{ $.Release.Name }}-{{ .name }}-{{ $.Values.metadata.commitHash }}.{{ $.Release.Namespace }}.svc.cluster.local
          port:
            number: 80
        headers:
          request:
            set:
              Knative-Serving-Namespace: {{ $.Release.Namespace }}
              Knative-Serving-Revision: {{ $.Release.Name }}-{{ .name }}-{{ $.Values.metadata.commitHash }}
---
{{- end }}
{{- end -}}
{{- end -}}
