// <auto-generated />
using System;
using LegalAiAr.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LegalAiAr.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260310162740_SeedSourcesAndCrawlerConfigs")]
    partial class SeedSourcesAndCrawlerConfigs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LegalAiAr.Core.Entities.Citation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CitationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CsjnSummaryId")
                        .HasColumnType("int");

                    b.Property<string>("ExternalAlias")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("SourceRulingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TargetRulingId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExternalAlias");

                    b.HasIndex("SourceRulingId");

                    b.HasIndex("TargetRulingId");

                    b.ToTable("Citations", (string)null);
                });

            modelBuilder.Entity("LegalAiAr.Core.Entities.Court", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Instance")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("JurisdictionArea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Territory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Courts", (string)null);
                });

            modelBuilder.Entity("LegalAiAr.Core.Entities.CrawlerConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CronExpression")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastCrawledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastCrawledStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("LastDocumentCount")
                        .HasColumnType("int");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SourceId")
                        .IsUnique();

                    b.ToTable("CrawlerConfigs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEnabled = true,
                            SourceId = 1,
                            UpdatedAt = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEnabled = false,
                            SourceId = 2,
                            UpdatedAt = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEnabled = false,
                            SourceId = 3,
                            UpdatedAt = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEnabled = false,
                            SourceId = 4,
                            UpdatedAt = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("LegalAiAr.Core.Entities.Judge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CurrentCourtId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CurrentCourtId");

                    b.ToTable("Judges", (string)null);
                });

            modelBuilder.Entity("LegalAiAr.Core.Entities.Keyword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ExternalCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Keywords", (string)null);
                });

            modelBuilder.Entity("LegalAiAr.Core.Entities.Ruling", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnalysisId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BlobPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CaseNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CaseTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("CourtId")
                        .HasColumnType("int");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Holding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IndexedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Instance")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsUnconstitutional")
                        .HasColumnType("bit");

                    b.Property<string>("Jurisdiction")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("JurisdictionArea")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ResourceType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("RulingDate")
                        .HasColumnType("date");

                    b.Property<string>("RulingDirection")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SubjectArea")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.HasIndex("CourtId");

                    b.HasIndex("SourceId", "ExternalId");

                    b.ToTable("Rulings", (string)null);
                });

            modelBuilder.Entity("LegalAiAr.Core.Entities.RulingJudge", b =>
                {
                    b.Property<Guid>("RulingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("JudgeId")
                        .HasColumnType("int");

                    b.Property<string>("ParticipationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RulingId", "JudgeId");

                    b.HasIndex("JudgeId");

                    b.ToTable("RulingJudges", (string)null);
                });

            modelBuilder.Entity("LegalAiAr.Core.Entities.RulingKeyword", b =>
                {
                    b.Property<Guid>("RulingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KeywordId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("RulingId", "KeywordId");

                    b.HasIndex("KeywordId");

                    b.ToTable("RulingKeywords", (string)null);
                });

            modelBuilder.Entity("LegalAiAr.Core.Entities.RulingStatute", b =>
                {
                    b.Property<Guid>("RulingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StatuteId")
                        .HasColumnType("int");

                    b.Property<string>("Articles")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("RulingId", "StatuteId");

                    b.HasIndex("StatuteId");

                    b.ToTable("RulingStatutes", (string)null);
                });

            modelBuilder.Entity("LegalAiAr.Core.Entities.Source", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Sources", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseUrl = "https://sjconsulta.csjn.gov.ar/sjconsulta/",
                            FullName = "Corte Suprema de Justicia de la Nación",
                            IsActive = true,
                            Name = "CSJN",
                            Strategy = "api-first"
                        },
                        new
                        {
                            Id = 2,
                            BaseUrl = "https://www.saij.gob.ar/",
                            FullName = "Sistema Argentino de Información Jurídica",
                            IsActive = true,
                            Name = "SAIJ",
                            Strategy = "html-pdf"
                        },
                        new
                        {
                            Id = 3,
                            BaseUrl = "https://www.pjn.gov.ar/",
                            FullName = "Poder Judicial de la Nación",
                            IsActive = true,
                            Name = "PJN",
                            Strategy = "html-pdf"
                        },
                        new
                        {
                            Id = 4,
                            BaseUrl = "https://www.scba.gov.ar/",
                            FullName = "Suprema Corte de Justicia de la Provincia de Buenos Aires",
                            IsActive = true,
                            Name = "SCBA",
                            Strategy = "html-pdf"
                        });
                });

            modelBuilder.Entity("LegalAiAr.Core.Entities.Statute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Statutes", (string)null);
                });

            modelBuilder.Entity("LegalAiAr.Core.Entities.Citation", b =>
                {
                    b.HasOne("LegalAiAr.Core.Entities.Ruling", "SourceRuling")
                        .WithMany("OutboundCitations")
                        .HasForeignKey("SourceRulingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LegalAiAr.Core.Entities.Ruling", "TargetRuling")
                        .WithMany("InboundCitations")
                        .HasForeignKey("TargetRulingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SourceRuling");

                    b.Navigation("TargetRuling");
                });

            modelBuilder.Entity("LegalAiAr.Core.Entities.CrawlerConfig", b =>
                {
                    b.HasOne("LegalAiAr.Core.Entities.Source", "Source")
                        .WithMany("CrawlerConfigs")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("LegalAiAr.Core.Entities.Judge", b =>
                {
                    b.HasOne("LegalAiAr.Core.Entities.Court", "CurrentCourt")
                        .WithMany("Judges")
                        .HasForeignKey("CurrentCourtId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CurrentCourt");
                });

            modelBuilder.Entity("LegalAiAr.Core.Entities.Ruling", b =>
                {
                    b.HasOne("LegalAiAr.Core.Entities.Court", "Court")
                        .WithMany("Rulings")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LegalAiAr.Core.Entities.Source", "Source")
                        .WithMany("Rulings")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Court");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("LegalAiAr.Core.Entities.RulingJudge", b =>
                {
                    b.HasOne("LegalAiAr.Core.Entities.Judge", "Judge")
                        .WithMany("RulingJudges")
                        .HasForeignKey("JudgeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LegalAiAr.Core.Entities.Ruling", "Ruling")
                        .WithMany("RulingJudges")
                        .HasForeignKey("RulingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Judge");

                    b.Navigation("Ruling");
                });

            modelBuilder.Entity("LegalAiAr.Core.Entities.RulingKeyword", b =>
                {
                    b.HasOne("LegalAiAr.Core.Entities.Keyword", "Keyword")
                        .WithMany("RulingKeywords")
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LegalAiAr.Core.Entities.Ruling", "Ruling")
                        .WithMany("RulingKeywords")
                        .HasForeignKey("RulingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Keyword");

                    b.Navigation("Ruling");
                });

            modelBuilder.Entity("LegalAiAr.Core.Entities.RulingStatute", b =>
                {
                    b.HasOne("LegalAiAr.Core.Entities.Ruling", "Ruling")
                        .WithMany("RulingStatutes")
                        .HasForeignKey("RulingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegalAiAr.Core.Entities.Statute", "Statute")
                        .WithMany("RulingStatutes")
                        .HasForeignKey("StatuteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ruling");

                    b.Navigation("Statute");
                });

            modelBuilder.Entity("LegalAiAr.Core.Entities.Court", b =>
                {
                    b.Navigation("Judges");

                    b.Navigation("Rulings");
                });

            modelBuilder.Entity("LegalAiAr.Core.Entities.Judge", b =>
                {
                    b.Navigation("RulingJudges");
                });

            modelBuilder.Entity("LegalAiAr.Core.Entities.Keyword", b =>
                {
                    b.Navigation("RulingKeywords");
                });

            modelBuilder.Entity("LegalAiAr.Core.Entities.Ruling", b =>
                {
                    b.Navigation("InboundCitations");

                    b.Navigation("OutboundCitations");

                    b.Navigation("RulingJudges");

                    b.Navigation("RulingKeywords");

                    b.Navigation("RulingStatutes");
                });

            modelBuilder.Entity("LegalAiAr.Core.Entities.Source", b =>
                {
                    b.Navigation("CrawlerConfigs");

                    b.Navigation("Rulings");
                });

            modelBuilder.Entity("LegalAiAr.Core.Entities.Statute", b =>
                {
                    b.Navigation("RulingStatutes");
                });
#pragma warning restore 612, 618
        }
    }
}
